Write-Host "PhoneCodex supports Windows through WSL2."
Write-Host "Native Windows is not the primary path for Codex TUI + ttyd + tmux."
Write-Host "If WSL is not installed, run this from an elevated PowerShell:"
Write-Host "  wsl --install -d Ubuntu"
Write-Host ""
Write-Host "Then open Ubuntu and run:"
Write-Host "  sudo apt update"
Write-Host "  sudo apt install -y python3 python3-pip tmux tailscale"
Write-Host "  sudo apt install -y ttyd  # if available in your apt repository"
Write-Host "  git clone https://github.com/MarkTaylorTsai/phonecodex.git"
Write-Host "  cd phonecodex"
Write-Host "  python3 -m pip install --user ."
Write-Host "  phonecodex doctor"
Write-Host "  phonecodex service install --mode tailscale"
Write-Host "  phonecodex codex my-project /path/to/project --mode tailscale"
Write-Host ""
Write-Host "If WSL systemd is unavailable, run these in separate WSL terminals:"
Write-Host "  phonecodex serve-index --bind-host 127.0.0.1 --port 7680"
Write-Host "  phonecodex run-session my-project"
