Write-Host "PhoneCodex supports Windows through WSL2."
Write-Host "If WSL is not installed, run this from an elevated PowerShell:"
Write-Host "  wsl --install -d Ubuntu"
Write-Host ""
Write-Host "Then open Ubuntu and run:"
Write-Host "  sudo apt update"
Write-Host "  sudo apt install -y python3 python3-pip tmux"
Write-Host "  git clone https://github.com/MarkTaylorTsai/phonecodex.git"
Write-Host "  cd phonecodex"
Write-Host "  python3 -m pip install --user ."
Write-Host "  phonecodex doctor"
Write-Host "  phonecodex install"
